name        : docbook-xml
version     : 4.5
release     : 10
source      :
    - https://www.docbook.org/xml/4.5/docbook-xml-4.5.zip : 4e4e037a2b83c98c6c94818390d4bdd3f6e10f6ec62dd79188594e26190dc7b4
    - https://github.com/docbook/xslt10-stylesheets/releases/download/release%2F1.79.2/docbook-xsl-nons-1.79.2.tar.bz2 : ee8b9eca0b7a8f89075832a2da7534bce8c5478fc8fc2676f512d5d87d832102
    - https://github.com/docbook/xslt10-stylesheets/releases/download/release%2F1.79.2/docbook-xsl-1.79.2.tar.bz2 : 316524ea444e53208a2fb90eeb676af755da96e1417835ba5f5eb719c81fa371
    - https://www.docbook.org/sgml/4.5/docbook-4.5.zip : 8043e514e80c6c19cb146b5d37937d1305bf3abf9b0097c36df7f70f611cdf43
license     : GPL-3.0-or-later
component   : programming
summary     : XML data files for DocBook
replaces    :
    - docbook-xsl
builddeps   :
    - docbook-xml
description : |
    The DocBook XML DTD-4.5 package contains document type definitions for verification of XML data files against the DocBook rule set. These are useful for structuring books and software documentation to a standard allowing you to utilize transformations already written for that standard.
install    : |
        root="/usr/share/xml/docbook/xml-dtd-${version}"
        full_root="${installdir}/${root}"

        install -D -m 00644 docbook.cat "${full_root}/docbook.cat"
        install -m 00644 *.dtd "${full_root}"
        install -m 00644 *.mod "${full_root}"
        cp -Rv ent/ "${full_root}/."
        install -D -d -m 00755 "${installdir}/etc/xml"

        mkdir docbook-sgml && pushd docbook-sgml
        unzip $sources/docbook-${version}.zip
        sed -i -e '/ISO 8879/d' -e '/gml/d' docbook.cat
        install -v -d  $installdir/usr/share/sgml/docbook/sgml-dtd-4.5
        install -v docbook.cat $installdir/usr/share/sgml/docbook/sgml-dtd-4.5/catalog
        cp -v -af *.dtd *.mod *.dcl  $installdir/usr/share/sgml/docbook/sgml-dtd-4.5

        unset version

        cat >> ${installdir}/usr/share/sgml/docbook/sgml-dtd-4.5/catalog << "EOF"
        -- Begin Single Major Version catalog changes --

        PUBLIC "-//OASIS//DTD DocBook V4.4//EN" "docbook.dtd"
        PUBLIC "-//OASIS//DTD DocBook V4.3//EN" "docbook.dtd"
        PUBLIC "-//OASIS//DTD DocBook V4.2//EN" "docbook.dtd"
        PUBLIC "-//OASIS//DTD DocBook V4.1//EN" "docbook.dtd"
        PUBLIC "-//OASIS//DTD DocBook V4.0//EN" "docbook.dtd"

        -- End Single Major Version catalog changes --
        EOF

        mkdir -p ${installdir}/etc/sgml
        echo 'CATALOG "/usr/share/sgml/docbook/sgml-dtd-4.5/catalog"' > ${installdir}/etc/sgml/catalog
        popd # docbook-sgml

        docbookVersion="1.79.2"
        _install_docbook() {
            src="$1"
            kind="$2"

            tar xvf "${sources}/docbook-${src}-${docbookVersion}.tar.bz2"
            root="/usr/share/xml/docbook/${kind}-stylesheets-${docbookVersion}"
            full_root="${installdir}/${root}"

            pushd "docbook-${src}-${docbookVersion}"
            %patch -p2 < $pkgfiles/docbook-style-${kind}-non-recursive-string-subst.patch

            install -d -D -m 00755 "${full_root}"

            for item in VERSION common eclipse epub extensions fo highlighting html \
            htmlhelp images javahelp lib manpages params profiling \
            roundtrip slides template tests tools webhelp website \
            xhtml xhtml-1_1 ; \
            do
            cp -Rv "${item}" "${full_root}/."
            done

            # Create the .xsl symlink
            ln -sv "${root}/VERSION" "${full_root}/VERSION.xsl"
            popd
        }
        _install_docbook "xsl-nons" "xsl"
        _install_docbook "xsl"      "xsl-ns"

        mkdir -p $installdir/etc/xml

        xmlCatalogFile="${installdir}/etc/xml/catalog"
        docbookFile="${installdir}/etc/xml/docbook"
        xmlcatalog  --noout --create $installdir/etc/xml/docbook
        xmlcatalog  --noout --create $installdir/etc/xml/catalog
        XML_CATALOG_FILES=$installdir/etc/xml/docbook  xmlcatalog --add "public" "-//OASIS//DTD DocBook XML V4.5//EN" "http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd" $installdir/etc/xml/docbook
        XML_CATALOG_FILES=$installdir/etc/xml/docbook  xmlcatalog --add "public" "-//OASIS//DTD DocBook XML CALS Table Model V4.5//EN" "file:///usr/share/xml/docbook/xml-dtd-4.5/calstblx.dtd" $installdir/etc/xml/docbook

        export XML_CATALOG_FILES=$installdir/etc/xml/docbook
        xmlcatalog --noout --add "public" \
        "-//OASIS//DTD DocBook XML V4.5//EN" \
        "http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd" \
        $docbookFile
        xmlcatalog --noout --add "public" \
        "-//OASIS//DTD DocBook XML CALS Table Model V4.5//EN" \
        "file:///usr/share/xml/docbook/xml-dtd-4.5/calstblx.dtd" \
        $docbookFile
        xmlcatalog --noout --add "public" \
        "-//OASIS//DTD XML Exchange Table Model 19990315//EN" \
        "file:///usr/share/xml/docbook/xml-dtd-4.5/soextblx.dtd" \
        $docbookFile
        xmlcatalog --noout --add "public" \
        "-//OASIS//ELEMENTS DocBook XML Information Pool V4.5//EN" \
        "file:///usr/share/xml/docbook/xml-dtd-4.5/dbpoolx.mod" \
        $docbookFile
        xmlcatalog --noout --add "public" \
        "-//OASIS//ELEMENTS DocBook XML Document Hierarchy V4.5//EN" \
        "file:///usr/share/xml/docbook/xml-dtd-4.5/dbhierx.mod" \
        $docbookFile
        xmlcatalog --noout --add "public" \
        "-//OASIS//ELEMENTS DocBook XML HTML Tables V4.5//EN" \
        "file:///usr/share/xml/docbook/xml-dtd-4.5/htmltblx.mod" \
        $docbookFile
        xmlcatalog --noout --add "public" \
        "-//OASIS//ENTITIES DocBook XML Notations V4.5//EN" \
        "file:///usr/share/xml/docbook/xml-dtd-4.5/dbnotnx.mod" \
        $docbookFile
        xmlcatalog --noout --add "public" \
        "-//OASIS//ENTITIES DocBook XML Character Entities V4.5//EN" \
        "file:///usr/share/xml/docbook/xml-dtd-4.5/dbcentx.mod" \
        $docbookFile
        xmlcatalog --noout --add "public" \
        "-//OASIS//ENTITIES DocBook XML Additional General Entities V4.5//EN" \
        "file:///usr/share/xml/docbook/xml-dtd-4.5/dbgenent.mod" \
        $docbookFile
        xmlcatalog --noout --add "rewriteSystem" \
        "http://www.oasis-open.org/docbook/xml/4.5" \
        "file:///usr/share/xml/docbook/xml-dtd-4.5" \
        $docbookFile
        export XML_CATALOG_FILES=$installdir/etc/xml/catalog

        xmlcatalog --noout --add "rewriteURI" \
        "http://www.oasis-open.org/docbook/xml/4.5" \
        "file:///usr/share/xml/docbook/xml-dtd-4.5" \
        $xmlCatalogFile

        export XML_CATALOG_FILES=$installdir/etc/xml/docbook

        for DTDVERSION in 4.1.2 4.2 4.3 4.4 4.5
        do
                xmlcatalog  --noout --add "public" \
                "-//OASIS//DTD DocBook XML V$DTDVERSION//EN" \
                "http://www.oasis-open.org/docbook/xml/$DTDVERSION/docbookx.dtd" \
                $docbookFile
                xmlcatalog  --noout --add "rewriteSystem" \
                "http://www.oasis-open.org/docbook/xml/$DTDVERSION" \
                "file:///usr/share/xml/docbook/xml-dtd-4.5" \
                $docbookFile
                xmlcatalog --noout --add "rewriteURI" \
                "http://www.oasis-open.org/docbook/xml/$DTDVERSION" \
                "file:///usr/share/xml/docbook/xml-dtd-4.5" \
                $docbookFile

                export XML_CATALOG_FILES=$installdir/etc/xml/docbook

                xmlcatalog --noout --add "delegateSystem" \
                "http://www.oasis-open.org/docbook/xml/$DTDVERSION/" \
                "file:///etc/xml/docbook" \
                $xmlCatalogFile

                xmlcatalog --noout --add "delegateURI" \
                "http://www.oasis-open.org/docbook/xml/$DTDVERSION/" \
                "file:///etc/xml/docbook" \
                $xmlCatalogFile
        done

        XML_CATALOG_FILES=$installdir/etc/xml/catalog

        # Now do docbook-xsl (nons) ..
        xmlcatalog --noout --add "rewriteSystem" \
           "http://cdn.docbook.org/release/xsl-nons/${docbookVersion}" \
           "/usr/share/xml/docbook/xsl-stylesheets-${docbookVersion}" \
        $xmlCatalogFile
        xmlcatalog --noout --add "rewriteURI" \
           "http://cdn.docbook.org/release/xsl-nons/${docbookVersion}" \
           "/usr/share/xml/docbook/xsl-stylesheets-${docbookVersion}" \
        $xmlCatalogFile
        xmlcatalog --noout --add "rewriteSystem" \
           "http://cdn.docbook.org/release/xsl-nons/current" \
           "/usr/share/xml/docbook/xsl-stylesheets-${docbookVersion}" \
        $xmlCatalogFile
        xmlcatalog  --noout --add "rewriteURI" \
           "http://cdn.docbook.org/release/xsl-nons/current" \
           "/usr/share/xml/docbook/xsl-stylesheets-${docbookVersion}" \
        $xmlCatalogFile

        # And do docbook-xsl (ns)...
        xmlcatalog --noout --add "rewriteSystem" \
           "http://cdn.docbook.org/release/xsl/${docbookVersion}" \
           "/usr/share/xml/docbook/xsl-ns-stylesheets-${docbookVersion}" \
        $xmlCatalogFile
        xmlcatalog --noout --add "rewriteURI" \
           "http://cdn.docbook.org/release/xsl/${docbookVersion}" \
           "/usr/share/xml/docbook/xsl-ns-stylesheets-${docbookVersion}" \
        $xmlCatalogFile
        xmlcatalog --noout --add "rewriteSystem" \
           "http://cdn.docbook.org/release/xsl/current" \
           "/usr/share/xml/docbook/xsl-ns-stylesheets-${docbookVersion}" \
        $xmlCatalogFile
        xmlcatalog  --noout --add "rewriteURI" \
           "http://cdn.docbook.org/release/xsl/current" \
           "/usr/share/xml/docbook/xsl-ns-stylesheets-${docbookVersion}" \
        $xmlCatalogFile


        # Keep the old sourceforge URIs for now
        xmlcatalog --noout --add "rewriteSystem" \
           "http://docbook.sourceforge.net/release/xsl/current" \
           "/usr/share/xml/docbook/xsl-stylesheets-${docbookVersion}" \
        $xmlCatalogFile
        xmlcatalog --noout --add "rewriteURI" \
           "http://docbook.sourceforge.net/release/xsl/current" \
           "/usr/share/xml/docbook/xsl-stylesheets-${docbookVersion}" \
        $xmlCatalogFile
        xmlcatalog --noout --add "rewriteSystem" \
           "http://docbook.sourceforge.net/release/xsl-ns/current" \
           "/usr/share/xml/docbook/xsl-ns-stylesheets-${docbookVersion}" \
        $xmlCatalogFile
        xmlcatalog --noout --add "rewriteURI" \
           "http://docbook.sourceforge.net/release/xsl-ns/current" \
           "/usr/share/xml/docbook/xsl-ns-stylesheets-${docbookVersion}" \
        $xmlCatalogFile

        XML_CATALOG_FILES=$installdir/etc/xml/catalog xmlcatalog --noout --add "delegatePublic" "-//OASIS//DTD DocBook XML" "file:///etc/xml/docbook" $xmlCatalogFile
