name        : docbook-xml
version     : 4.5
release     : 5
source      :
    - http://www.docbook.org/xml/4.5/docbook-xml-4.5.zip : 4e4e037a2b83c98c6c94818390d4bdd3f6e10f6ec62dd79188594e26190dc7b4
    - http://downloads.sourceforge.net/docbook/docbook-xsl-1.77.1.tar.bz2 : 24c6c4413f71f9a2c000fa21be76c58f53db1baa42f17b02845e1c2c0aeb7cd5
license     :
    - GPLv3+
summary     : XML data files for DocBook
replaces    :
    - docbook-xsl
description : |
    The DocBook XML DTD-4.5 package contains document type definitions for verification of XML data files against the DocBook rule set. These are useful for structuring books and software documentation to a standard allowing you to utilize transformations already written for that standard.
install    : |
    root="/usr/share/xml/docbook/xml-dtd-${version}"
    full_root="${installdir}/${root}"
    
    install -D -m 00644 docbook.cat "${full_root}/docbook.cat"
    install -m 00644 *.dtd "${full_root}"
    install -m 00644 *.mod "${full_root}"
    cp -Rv ent/ "${full_root}/."
    install -D -d -m 00755 "${installdir}/etc/xml"
    
    docbookVersion="1.77.1"
    tar xvf "${sources}/docbook-xsl-${docbookVersion}.tar.bz2"
    root="/usr/share/xml/docbook/xsl-stylesheets-${docbookVersion}"
    full_root="${installdir}/${root}"
    pushd "docbook-xsl-${docbookVersion}"
    
    install -d -D -m 00755 "${full_root}"
    
    for item in VERSION common eclipse epub extensions fo highlighting html \
        htmlhelp images javahelp lib manpages params profiling \
        roundtrip slides template tests tools webhelp website \
        xhtml xhtml-1_1 ; \
    do
        cp -Rv "${item}" "${full_root}/."
    done
    
    # Create the .xsl symlink
    ln -sv "${root}/VERSION" "${full_root}/VERSION.xsl"
    popd # docbook-xsl
    
    xmlCatalogFile="${installdir}/etc/xml/catalog"
    # The following is all taken from LFS wiki:
    if [ ! -e $xmlCatalogFile ]; then
        xmlcatalog --noout --create $xmlCatalogFile
    fi &&
    xmlcatalog --noout --add "public" \
        "-//OASIS//DTD DocBook XML V4.5//EN" \
        "http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd" \
        $xmlCatalogFile &&
    xmlcatalog --noout --add "public" \
        "-//OASIS//DTD DocBook XML CALS Table Model V4.5//EN" \
        "file:///usr/share/xml/docbook/xml-dtd-4.5/calstblx.dtd" \
        $xmlCatalogFile &&
    xmlcatalog --noout --add "public" \
        "-//OASIS//DTD XML Exchange Table Model 19990315//EN" \
        "file:///usr/share/xml/docbook/xml-dtd-4.5/soextblx.dtd" \
        $xmlCatalogFile &&
    xmlcatalog --noout --add "public" \
        "-//OASIS//ELEMENTS DocBook XML Information Pool V4.5//EN" \
        "file:///usr/share/xml/docbook/xml-dtd-4.5/dbpoolx.mod" \
        $xmlCatalogFile &&
    xmlcatalog --noout --add "public" \
        "-//OASIS//ELEMENTS DocBook XML Document Hierarchy V4.5//EN" \
        "file:///usr/share/xml/docbook/xml-dtd-4.5/dbhierx.mod" \
        $xmlCatalogFile &&
    xmlcatalog --noout --add "public" \
        "-//OASIS//ELEMENTS DocBook XML HTML Tables V4.5//EN" \
        "file:///usr/share/xml/docbook/xml-dtd-4.5/htmltblx.mod" \
        $xmlCatalogFile &&
    xmlcatalog --noout --add "public" \
        "-//OASIS//ENTITIES DocBook XML Notations V4.5//EN" \
        "file:///usr/share/xml/docbook/xml-dtd-4.5/dbnotnx.mod" \
        $xmlCatalogFile &&
    xmlcatalog --noout --add "public" \
        "-//OASIS//ENTITIES DocBook XML Character Entities V4.5//EN" \
        "file:///usr/share/xml/docbook/xml-dtd-4.5/dbcentx.mod" \
        $xmlCatalogFile &&
    xmlcatalog --noout --add "public" \
        "-//OASIS//ENTITIES DocBook XML Additional General Entities V4.5//EN" \
        "file:///usr/share/xml/docbook/xml-dtd-4.5/dbgenent.mod" \
        $xmlCatalogFile &&
    xmlcatalog --add "rewriteSystem" \
        "http://www.oasis-open.org/docbook/xml/4.5" \
        "file:///usr/share/xml/docbook/xml-dtd-4.5" \
        $xmlCatalogFile &&
    xmlcatalog --add "rewriteURI" \
        "http://www.oasis-open.org/docbook/xml/4.5" \
        "file:///usr/share/xml/docbook/xml-dtd-4.5" \
        $xmlCatalogFile
    
    docbookFile="${installdir}/etc/xml/docbook"
    for DTDVERSION in 4.1.2 4.2 4.3 4.4
    do
      xmlcatalog --noout --add "public" \
        "-//OASIS//DTD DocBook XML V$DTDVERSION//EN" \
        "http://www.oasis-open.org/docbook/xml/$DTDVERSION/docbookx.dtd" \
        $docbookFile
      xmlcatalog --noout --add "rewriteSystem" \
        "http://www.oasis-open.org/docbook/xml/$DTDVERSION" \
        "file:///usr/share/xml/docbook/xml-dtd-4.5" \
        $docbookFile
      xmlcatalog --noout --add "rewriteURI" \
        "http://www.oasis-open.org/docbook/xml/$DTDVERSION" \
        "file:///usr/share/xml/docbook/xml-dtd-4.5" \
        $docbookFile
      xmlcatalog --noout --add "delegateSystem" \
        "http://www.oasis-open.org/docbook/xml/$DTDVERSION/" \
        "file:///etc/xml/docbook" \
        $xmlCatalogFile
      xmlcatalog --noout --add "delegateURI" \
        "http://www.oasis-open.org/docbook/xml/$DTDVERSION/" \
        "file:///etc/xml/docbook" \
        $xmlCatalogFile
    done
    
    # Now do docbook-xsl ..
    xmlcatalog --noout --add "rewriteSystem" \
           "http://docbook.sourceforge.net/release/xsl/${docbookVersion}" \
           "/usr/share/xml/docbook/xsl-stylesheets-${docbookVersion}" \
    $xmlCatalogFile &&
    xmlcatalog --noout --add "rewriteURI" \
           "http://docbook.sourceforge.net/release/xsl/${docbookVersion}" \
           "/usr/share/xml/docbook/xsl-stylesheets-${docbookVersion}" \
    $xmlCatalogFile &&
    xmlcatalog --noout --add "rewriteSystem" \
           "http://docbook.sourceforge.net/release/xsl/current" \
           "/usr/share/xml/docbook/xsl-stylesheets-${docbookVersion}" \
    $xmlCatalogFile &&
    xmlcatalog  --add "rewriteURI" \
           "http://docbook.sourceforge.net/release/xsl/current" \
           "/usr/share/xml/docbook/xsl-stylesheets-${docbookVersion}" \
    $xmlCatalogFile
    
    xmlcatalog --noout --add "delegatePublic" "-//OASIS//DTD DocBook XML" "file:///usr/share/xml/docbook-${version}" ${installdir}/etc/xml/catalog

